### ISSUE TITLE
running instruction

### ISSUE THREAD

**Issue by kaishijeng** [doncat99/StockRecommendSystem#1]
Can you add how to run in the README?
I don't see instructions of how to do data fetching and stock processing. 
Thanks,

**Comment by doncat99** [comment]
Instruction added

**Comment by kaishijeng** [comment]
I am able to run your code with your instruction.
However, I sync up with your latest code today and Reinforcement, python ./runner.py is not working anymore with the following error. Any idea?

Using TensorFlow backend.
/usr/local/lib/python2.7/dist-packages/google/protobuf/__init__.py:37: UserWarning: Module numpy was already imported from /usr/local/lib/python2.7/dist-packages/numpy/__init__.pyc, but /usr/lib/python2.7/dist-packages is being added to sys.path
  __import__('pkg_resources').declare_namespace(__name__)
/usr/local/lib/python2.7/dist-packages/google/protobuf/__init__.py:37: UserWarning: Module six was already imported from /usr/local/lib/python2.7/dist-packages/six.pyc, but /usr/lib/python2.7/dist-packages is being added to sys.path
  __import__('pkg_resources').declare_namespace(__name__)
Error parsing command line: unrecognised option '--storageEngine'
try 'mongod --help' for more information
('init cash: ', 100000)
initial Config...
initial DB Client...
Traceback (most recent call last):
  File "./runner.py", line 68, in <module>
    rf_run()
  File "./runner.py", line 31, in rf_run
    env_train = Simulator(['AMD', 'NVDA'], dt.datetime(2006, 1, 4), dt.datetime(2016, 12, 30))
  File "/home/fc/2TB/src/StockRecommendSystem/Source/ReinforcementLearning/environment.py", line 81, in __init__
    self.date = prices_all.index[0]
  File "/usr/local/lib/python2.7/dist-packages/pandas/indexes/base.py", line 1423, in __getitem__
    return getitem(key)
IndexError: index 0 is out of bounds for axis 0 with size 0
