### ISSUE TITLE
runner.py doesn't work anymore with the latest code

### ISSUE THREAD

**Issue by kaishijeng** [doncat99/StockRecommendSystem#2]
I am able to run your code with your instruction a couple days ago.
However, when I sync up with your latest code today and  python ./runner.py in ReinforcementLearning is not working anymore with the following error. Any idea?

Using TensorFlow backend.
/usr/local/lib/python2.7/dist-packages/google/protobuf/init.py:37: UserWarning: Module numpy was already imported from /usr/local/lib/python2.7/dist-packages/numpy/init.pyc, but /usr/lib/python2.7/dist-packages is being added to sys.path
import('pkg_resources').declare_namespace(name)
/usr/local/lib/python2.7/dist-packages/google/protobuf/init.py:37: UserWarning: Module six was already imported from /usr/local/lib/python2.7/dist-packages/six.pyc, but /usr/lib/python2.7/dist-packages is being added to sys.path
import('pkg_resources').declare_namespace(name)
Error parsing command line: unrecognised option '--storageEngine'
try 'mongod --help' for more information
('init cash: ', 100000)
initial Config...
initial DB Client...
Traceback (most recent call last):
File "./runner.py", line 68, in 
rf_run()
File "./runner.py", line 31, in rf_run
env_train = Simulator(['AMD', 'NVDA'], dt.datetime(2006, 1, 4), dt.datetime(2016, 12, 30))
File "~/src/StockRecommendSystem/Source/ReinforcementLearning/environment.py", line 81, in init
self.date = prices_all.index[0]
File "/usr/local/lib/python2.7/dist-packages/pandas/indexes/base.py", line 1423, in getitem
return getitem(key)
IndexError: index 0 is out of bounds for axis 0 with size 0

**Comment by doncat99** [comment]
thanks for the attentions, please update the source code in one or two days later. 
the database structure is currently under frequently redesign for a bigger picture requirement. 
In these two days, I can't guarantee the integrity of the whole source code.
again, sorry for the inconvenient.

**Comment by doncat99** [comment]
@kaishijeng you can now update the source code, it is fixed.
